/* Modelo académico del tema 6. Tarifa por noche y permisos: propuestas para demostrar el flujo. */
(function(root){
'use strict';
const perms={Administrador:['habitaciones','huespedes','disponibilidad','reservas','checkin','checkout','usuarios','informes'],Encargado:['huespedes','disponibilidad','reservas','checkin','checkout']};
const next=a=>Math.max(0,...a.map(x=>x.id))+1;
const fail=t=>{throw new Error(t)};
const int=(v,min=1)=>{const n=Number(v);if(String(v).trim()===''||!Number.isSafeInteger(n)||n<min)fail('Ingrese un número entero válido.');return n};
const date=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)fail('Fecha inválida.');return s};
const interval=(a,b)=>{date(a);date(b);if(b<=a)fail('La salida debe ser posterior a la entrada.')};
const nights=(a,b)=>Math.round((Date.parse(b+'T00:00:00Z')-Date.parse(a+'T00:00:00Z'))/86400000);
function seed(){return {roles:[{id:1,nombre:'Administrador'},{id:2,nombre:'Encargado'}],usuarios:[{id:1,nombre:'admin_demo',rolId:1,activo:true},{id:2,nombre:'encargado_demo',rolId:2,activo:true}],habitaciones:[{id:1,numero:'201',capacidad:2,orientacion:'Norte'},{id:2,numero:'202',capacidad:2,orientacion:'Sur'},{id:3,numero:'305',capacidad:3,orientacion:'Este'}],huespedes:[{id:1,identificacion:'DEMO-01',nombres:'Ana',apellidos:'Ejemplo'},{id:2,identificacion:'DEMO-02',nombres:'Luis',apellidos:'Ejemplo'}],reservas:[],estadias:[],participaciones:[]}}
function authorize(d,user,op){const u=d.usuarios.find(x=>x.id===Number(user)&&x.activo);const role=d.roles.find(x=>x.id===u?.rolId);if(!u||!perms[role.nombre]?.includes(op))fail('El perfil seleccionado no tiene permiso para esta operación.');return u}
function occupied(d,room){return d.estadias.some(s=>s.habitacionId===room&&s.estado==='ACTIVA')}
function available(d,a,b,count=1,skipReservation=null){interval(a,b);count=int(count);return d.habitaciones.filter(h=>h.capacidad>=count&&!d.reservas.some(r=>r.id!==skipReservation&&r.habitacionId===h.id&&['REGISTRADA','CHECK_IN'].includes(r.estado)&&a<r.salida&&b>r.entrada)&&!d.estadias.some(s=>s.habitacionId===h.id&&s.estado==='ACTIVA'&&a<s.salidaPrevista&&b>s.entrada))}
function room(d,user,input){authorize(d,user,'habitaciones');const numero=String(input.numero||'').trim(),orientacion=String(input.orientacion||'').trim(),capacidad=int(input.capacidad);if(!numero||!orientacion)fail('Complete número y orientación.');if(d.habitaciones.some(h=>h.numero.toLowerCase()===numero.toLowerCase()&&h.id!==input.id))fail('Número de habitación duplicado.');const old=d.habitaciones.find(h=>h.id===input.id);if(old){if(d.estadias.some(s=>s.habitacionId===old.id&&s.estado==='ACTIVA')||d.reservas.some(r=>r.habitacionId===old.id&&r.estado==='REGISTRADA'))fail('No se modifica una habitación con estadías o reservas vigentes.');Object.assign(old,{numero,orientacion,capacidad});return old}const h={id:next(d.habitaciones),numero,orientacion,capacidad};d.habitaciones.push(h);return h}
function guest(d,user,input){authorize(d,user,'huespedes');const identificacion=String(input.identificacion||'').trim().toUpperCase(),nombres=String(input.nombres||'').trim(),apellidos=String(input.apellidos||'').trim();if(!identificacion||!nombres||!apellidos)fail('Complete identificación, nombres y apellidos.');if(d.huespedes.some(h=>h.identificacion===identificacion))fail('La identificación ya está registrada; seleccione ese huésped.');const h={id:next(d.huespedes),identificacion,nombres,apellidos};d.huespedes.push(h);return h}
function reservation(d,user,input){authorize(d,user,'reservas');const r=input.id?d.reservas.find(x=>x.id===input.id):null;if(input.id&&(!r||r.estado!=='REGISTRADA'))fail('Sólo se modifica una reserva REGISTRADA.');const h=d.huespedes.find(x=>x.id===Number(input.titularId)),roomId=Number(input.habitacionId),cantidad=int(input.cantidad);if(!h)fail('Seleccione un titular registrado.');interval(input.entrada,input.salida);if(!available(d,input.entrada,input.salida,cantidad,r?.id).some(x=>x.id===roomId))fail('Capacidad insuficiente o habitación no disponible.');const values={titularId:h.id,habitacionId:roomId,entrada:input.entrada,salida:input.salida,cantidad,estado:'REGISTRADA'};if(r){Object.assign(r,values);return r}const added={id:next(d.reservas),...values};d.reservas.push(added);return added}
function cancel(d,user,id){authorize(d,user,'reservas');const r=d.reservas.find(x=>x.id===Number(id));if(!r||r.estado!=='REGISTRADA')fail('Sólo se cancela una reserva REGISTRADA.');r.estado='CANCELADA';return r}
function checkin(d,user,input){authorize(d,user,'checkin');const r=input.reservaId?d.reservas.find(x=>x.id===Number(input.reservaId)):null;if(input.reservaId&&(!r||r.estado!=='REGISTRADA'))fail('Seleccione una reserva REGISTRADA.');const roomId=r?r.habitacionId:Number(input.habitacionId),entrada=r?r.entrada:input.entrada,salida=r?r.salida:input.salida;interval(entrada,salida);const ids=[...new Set((input.huespedIds||[]).map(Number))];if(!ids.length||ids.length!==(input.huespedIds||[]).length||ids.some(id=>!d.huespedes.some(h=>h.id===id)))fail('Seleccione huéspedes registrados sin duplicados.');if(r&&ids.length!==r.cantidad)fail('Debe identificar a todos los pasajeros de la reserva.');if(!available(d,entrada,salida,ids.length,r?.id).some(h=>h.id===roomId)||occupied(d,roomId))fail('La habitación no está disponible o se supera su capacidad.');if(d.participaciones.some(p=>ids.includes(p.huespedId)&&d.estadias.some(s=>s.id===p.estadiaId&&s.estado==='ACTIVA')))fail('Un huésped seleccionado ya tiene una estadía activa.');const s={id:next(d.estadias),habitacionId:roomId,reservaId:r?.id||null,entrada,salidaPrevista:salida,salidaReal:null,estado:'ACTIVA'};d.estadias.push(s);ids.forEach(id=>d.participaciones.push({estadiaId:s.id,huespedId:id,tarifaCLP:null,costoCLP:null}));if(r)r.estado='CHECK_IN';return s}
function quote(d,id,salida,rate){const s=d.estadias.find(x=>x.id===Number(id)&&x.estado==='ACTIVA');if(!s)fail('Seleccione una estadía ACTIVA.');interval(s.entrada,salida);const tarifa=int(rate,0),noches=nights(s.entrada,salida),ps=d.participaciones.filter(p=>p.estadiaId===s.id);if(!ps.length)fail('La estadía no tiene pasajeros identificados.');const costo=tarifa*noches,total=costo*ps.length;if(!Number.isSafeInteger(total))fail('El importe supera el rango permitido.');return {noches,tarifa,total,filas:ps.map(p=>({huespedId:p.huespedId,costoCLP:costo}))}}
function checkout(d,user,input){authorize(d,user,'checkout');const q=quote(d,input.estadiaId,input.salida,input.tarifaCLP),s=d.estadias.find(x=>x.id===Number(input.estadiaId));if(!input.confirmado)fail('Revise la cuenta y confirme la salida.');if(input.salida>s.salidaPrevista&&d.reservas.some(r=>r.id!==s.reservaId&&r.habitacionId===s.habitacionId&&r.estado==='REGISTRADA'&&r.entrada<input.salida&&r.salida>s.salidaPrevista))fail('La salida extendida entra en conflicto con otra reserva.');d.participaciones.filter(p=>p.estadiaId===s.id).forEach(p=>Object.assign(p,{tarifaCLP:q.tarifa,costoCLP:q.filas.find(f=>f.huespedId===p.huespedId).costoCLP}));s.nochesCobradas=q.noches;s.salidaReal=input.salida;s.estado='FINALIZADA';const r=d.reservas.find(x=>x.id===s.reservaId);if(r)r.estado='FINALIZADA';return q}
function user(d,actor,input){authorize(d,actor,'usuarios');const nombre=String(input.nombre||'').trim(),rolId=Number(input.rolId);if(!nombre||!d.roles.some(r=>r.id===rolId))fail('Complete el nombre de usuario y perfil.');if(d.usuarios.some(u=>u.nombre.toLowerCase()===nombre.toLowerCase()&&u.id!==input.id))fail('Usuario duplicado.');const old=d.usuarios.find(u=>u.id===input.id);if(old){if(old.id===Number(actor)&&(!input.activo||rolId!==old.rolId))fail('No cambie su propio acceso durante la sesión.');Object.assign(old,{nombre,rolId,activo:!!input.activo});return old}const u={id:next(d.usuarios),nombre,rolId,activo:true};d.usuarios.push(u);return u}
function reports(d,a,b){interval(a,b);const reservas=d.reservas.filter(r=>a<r.salida&&b>r.entrada),estadias=d.estadias.filter(s=>a<(s.salidaReal||s.salidaPrevista)&&b>s.entrada);return {reservas,estadias}}
const api={seed,authorize,available,occupied,room,guest,reservation,cancel,checkin,quote,checkout,user,reports,nights,perms};if(typeof module!=='undefined')module.exports=api;else root.Hotel=api;
})(typeof window!=='undefined'?window:globalThis);
