const assert=require('node:assert/strict');
const H=require('../prototipo/engine.js');
const d=H.seed(),admin=1,enc=2;
assert.throws(()=>H.room(d,enc,{numero:'500',capacidad:2,orientacion:'Norte'}),/permiso/);
assert.throws(()=>H.room(d,admin,{numero:'201',capacidad:2,orientacion:'Sur'}),/duplicado/);
assert.throws(()=>H.room(d,admin,{numero:'500',capacidad:1.5,orientacion:'Norte'}),/entero/);
assert.throws(()=>H.guest(d,enc,{identificacion:'DEMO-01',nombres:'Ana',apellidos:'Uno'}),/registrada/);
const r=H.reservation(d,enc,{titularId:1,habitacionId:1,entrada:'2026-10-01',salida:'2026-10-03',cantidad:2});
assert.throws(()=>H.reservation(d,enc,{titularId:1,habitacionId:1,entrada:'2026-10-02',salida:'2026-10-04',cantidad:1}),/disponible/);
assert.throws(()=>H.reservation(d,enc,{titularId:1,habitacionId:2,entrada:'2026-10-01',salida:'2026-10-03',cantidad:3}),/Capacidad/);
const adjacent=H.reservation(d,enc,{titularId:1,habitacionId:1,entrada:'2026-10-03',salida:'2026-10-05',cantidad:1});
assert.throws(()=>H.checkin(d,enc,{reservaId:r.id,huespedIds:[1]}),/todos/);
assert.throws(()=>H.checkin(d,enc,{reservaId:r.id,huespedIds:[1,1]}),/duplicados/);
const stay=H.checkin(d,enc,{reservaId:r.id,huespedIds:[1,2]});
assert.equal(d.participaciones.length,2);assert.equal(d.reservas[0].estado,'CHECK_IN');
assert.throws(()=>H.checkin(d,enc,{reservaId:r.id,huespedIds:[1,2]}),/REGISTRADA/);
assert.throws(()=>H.checkin(d,enc,{habitacionId:2,entrada:'2026-10-01',salida:'2026-10-03',huespedIds:[1]}),/activa/);
assert.throws(()=>H.quote(d,stay.id,'2026-10-03',''),/entero/);
assert.throws(()=>H.checkout(d,enc,{estadiaId:stay.id,salida:'2026-10-03',tarifaCLP:10000,confirmado:false}),/confirme/);
assert.throws(()=>H.checkout(d,enc,{estadiaId:stay.id,salida:'2026-10-04',tarifaCLP:10000,confirmado:true}),/conflicto/);
const q=H.checkout(d,enc,{estadiaId:stay.id,salida:'2026-10-03',tarifaCLP:10000,confirmado:true});
assert.equal(q.total,40000);assert.deepEqual(d.participaciones.map(p=>p.costoCLP),[20000,20000]);assert.equal(H.occupied(d,1),false);
assert.throws(()=>H.checkout(d,enc,{estadiaId:stay.id,salida:'2026-10-03',tarifaCLP:10000,confirmado:true}),/ACTIVA/);
H.reservation(d,enc,{...adjacent,id:adjacent.id,salida:'2026-10-06'});assert.equal(adjacent.salida,'2026-10-06');
H.cancel(d,enc,adjacent.id);assert.equal(adjacent.estado,'CANCELADA');assert(H.available(d,'2026-10-03','2026-10-06').some(h=>h.id===1));
assert.throws(()=>H.reservation(d,enc,{...adjacent,id:adjacent.id}),/REGISTRADA/);
const direct=H.checkin(d,enc,{habitacionId:2,entrada:'2026-10-06',salida:'2026-10-07',huespedIds:[1]});assert.equal(direct.reservaId,null);
assert.equal(H.reports(d,'2026-10-01','2026-10-04').estadias.length,1);
assert.throws(()=>H.user(d,admin,{nombre:'admin_demo',rolId:2}),/duplicado/);
assert.throws(()=>H.user(d,admin,{id:1,nombre:'admin_demo',rolId:2,activo:true}),/propio/);
console.log('Pruebas aprobadas: roles, duplicados, capacidad, fechas, solapamiento, reservas, pasajeros individuales, check-in directo, costo por huésped, check-out y reportes.');
