from pathlib import Path
import json,html,textwrap
ROOT=Path(__file__).resolve().parents[1];M=json.loads((ROOT/'modelo/sistema.json').read_text())
BASE='https://app.diagrams.net/?mode=device#Uhttps%3A%2F%2Fraw.githubusercontent.com%2FYutre3%2Fhotel-duerme-bien%2Fmain%2Fdiagramas-editables%2F'
repo='https://github.com/Yutre3/hotel-duerme-bien';site='https://yutre3.github.io/hotel-duerme-bien/'
def edit(k):return BASE+k+'.drawio'
columns={'Por hacer':['Validar identificación y reglas de habitación compartida','Validar tarifa y fórmula definitiva de cobro','Validar permisos y condiciones de gestión de reservas','Recibir rúbrica y retroalimentación de Evaluación 1'],'En curso':[],'En revisión':['Informe de requerimientos y entrevista simulada','Casos de uso, procesos y modelo de datos','Sketch, wireframes y mockups','Prueba académica del prototipo'],'Terminado':['Conservar los 11 materiales originales','Reconstruir diagramas nativos y enlazar el editor','Implementar pasajeros individuales y costos','Verificar procesos y publicar la entrega']}
kanban=[dict(estado=state,tarea=t) for state,tasks in columns.items() for t in tasks]
(ROOT/'planificacion/kanban.json').write_text(json.dumps(kanban,ensure_ascii=False,indent=2))
(ROOT/'planificacion/kanban.md').write_text('# Kanban · Duerme Bien\n\n| Estado | Tarea |\n|---|---|\n'+'\n'.join(f'| {r["estado"]} | {r["tarea"]} |' for r in kanban)+'\n\nTerminado indica trabajo técnico realizado. La revisión académica y la validación del hotel siguen pendientes.\n')
s=(ROOT/'scripts/construir_modelado.py').read_text();exec(s[:s.index('cases={')]);d=D('kanban','Kanban · Duerme Bien',1600,1080)
for i,(state,tasks) in enumerate(columns.items()):
 x=40+i*390;d.node('col'+str(i),state,x,100,360,850,'frame',fill='#edf4f7')
 for j,t in enumerate(tasks):d.node(f'task{i}-{j}','\n'.join(textwrap.wrap(t,29)),x+15,175+j*185,330,150)
 if not tasks:d.node('none','Sin tareas en curso',x+15,175,330,100)
d.save()
# Portada corta y todos los artefactos visibles, igual que la organización de referencia.
diagrams=[('Casos de uso · Operación','casos-de-uso'),('Casos de uso · Administración','casos-de-uso-administracion'),('Registro de reserva','flujo-reserva'),('Modificación y cancelación','flujo-gestion-reservas'),('Check-in','flujo-check-in'),('Check-out','flujo-check-out'),('Clases de dominio','diagrama-de-clases'),('Modelo lógico de base de datos','modelo-de-datos')]
md='# Sistema de Pasajeros · Hotel Duerme Bien\n\n**Tema 6 · Luis Huenchul**\n\n[Ver entrega]('+site+') · [Probar demo]('+site+'prototipo/) · [Informe completo](informe/informe-con-diagramas.pdf)\n\n## Entrega\n\n| Nº | Elemento | Ver | PDF | Editar |\n|---:|---|---|---|---|\n| 1 | Informe de requerimientos | [Documento](informe/requerimientos-y-modelado.md) | [Informe](informe/informe-con-diagramas.pdf) | — |\n'
for i,(name,key) in enumerate(diagrams,2):md+=f'| {i} | {name} | [Imagen](diagramas/{key}.svg) | [PDF](diagramas/{key}.pdf) | [diagrams.net]({edit(key)}) |\n'
md+='| 10 | Sketch | [Imagen](mockups/sketch.svg) | [PDF](mockups/sketch.pdf) | [diagrams.net]('+edit('sketch')+') |\n| 11 | Wireframes y mockups | [Nueve pantallas]('+site+'mockups/) | — | [Todas las vistas]('+edit('interfaces')+') |\n| 12 | Prototipo funcional | [Abrir demo]('+site+'prototipo/) | — | [Código](https://github.dev/Yutre3/hotel-duerme-bien/tree/main/prototipo) |\n| 13 | Kanban | [Tablero](planificacion/kanban.md) | [PDF](diagramas/kanban.pdf) | [diagrams.net]('+edit('kanban')+') |\n\n## Materiales\n\n[Archivos originales]('+repo+'/tree/main/fuentes) · [Referencias](informe/requerimientos-y-modelado.md#12-referencias) · [Pruebas](tests/)\n'
(ROOT/'README.md').write_text(md)
css='''*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#17384d;font-family:Arial,sans-serif;line-height:1.5}header,main{max-width:1120px;margin:auto;padding:28px 22px}header{padding-top:42px}h1{font-size:36px;line-height:1.15;margin:0 0 8px}h2{margin:0 0 18px;font-size:26px}p{margin:6px 0 20px}.actions,.links{display:flex;gap:12px;flex-wrap:wrap}.button{display:inline-block;padding:11px 17px;border-radius:8px;background:#16697a;color:white;text-decoration:none;font-weight:bold}.button.secondary{background:white;color:#16697a;border:1px solid #bdd0d6}.panel{background:white;border:1px solid #d6e0e4;border-radius:14px;padding:22px;margin-bottom:24px;box-shadow:0 5px 18px #183d5010}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.step{background:#edf4f6;border-radius:9px;padding:12px;font-weight:bold}.step span{display:block;color:#268394;font-size:13px}.demo{width:100%;height:900px;border:1px solid #cad9df;border-radius:10px;background:white}.deliverables{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.item{border:1px solid #d6e0e4;border-radius:9px;padding:14px}.item strong{display:block;margin-bottom:7px}.item a{color:#126479;margin-right:12px}footer{max-width:1120px;margin:0 auto;padding:0 22px 38px;color:#607784}@media(max-width:720px){header{padding-top:28px}h1{font-size:29px}.steps,.deliverables{grid-template-columns:1fr}.demo{height:760px}.panel{padding:16px}.button{width:100%;text-align:center}}'''
page=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Duerme Bien · Tema 6</title><style>{css}</style></head><body><header><h1>Sistema de Pasajeros · Hotel Duerme Bien</h1><p>Tema 6 · Luis Huenchul</p><div class="actions"><a class="button" href="#demo">Probar demo</a><a class="button secondary" href="informe/informe-con-diagramas.pdf">Informe completo</a><a class="button secondary" href="{repo}">Repositorio</a></div></header><main><section class="panel" id="demo"><h2>Demo funcional</h2><div class="steps"><div class="step"><span>PASO 1</span>Ingresar por perfil</div><div class="step"><span>PASO 2</span>Reservar y hacer check-in</div><div class="step"><span>PASO 3</span>Calcular y registrar check-out</div><div class="step"><span>PASO 4</span>Consultar informes</div></div><p class="actions"><a class="button" href="prototipo/">Abrir demo en pantalla completa</a><a class="button secondary" href="https://github.dev/Yutre3/hotel-duerme-bien/tree/main/prototipo">Editar código</a></p><iframe class="demo" src="prototipo/" title="Demo funcional de Duerme Bien"></iframe></section><section class="panel"><h2>Documentos y diagramas</h2><div class="deliverables">'''
for name,key in diagrams:
 page+=f'<div class="item"><strong>{name}</strong><a href="diagramas/{key}.svg">Ver</a><a href="diagramas/{key}.pdf">PDF</a><a href="{edit(key)}" target="_blank" rel="noopener">Editar</a></div>'
page+=f'''</div></section><section class="panel"><h2>Diseño de pantallas</h2><div class="links"><a class="button" href="mockups/">Ver wireframes y mockups</a><a class="button secondary" href="{edit("interfaces")}" target="_blank" rel="noopener">Editar las vistas</a><a class="button secondary" href="{edit("sketch")}" target="_blank" rel="noopener">Editar sketch</a></div></section><section class="panel"><h2>Material de entrega</h2><div class="links"><a href="planificacion/kanban.md">Kanban</a><a href="{repo}/tree/main/fuentes">Materiales originales</a><a href="{repo}/blob/main/informe/requerimientos-y-modelado.md#12-referencias">Referencias</a><a href="{repo}/tree/main/tests">Pruebas</a></div></section></main><footer>Hotel Duerme Bien · Tema 6</footer></body></html>'''
(ROOT/'index.html').write_text(page)
