from pathlib import Path
import json,html,textwrap
ROOT=Path(__file__).resolve().parents[1];M=json.loads((ROOT/'modelo/sistema.json').read_text())
BASE='https://app.diagrams.net/?mode=device#Uhttps%3A%2F%2Fraw.githubusercontent.com%2FYutre3%2Fhotel-duerme-bien%2Fmain%2Fdiagramas-editables%2F'
repo='https://github.com/Yutre3/hotel-duerme-bien';site='https://yutre3.github.io/hotel-duerme-bien/'
def edit(k):return BASE+k+'.drawio'
columns={'Por hacer':['Validar identificación y reglas de habitación compartida','Validar tarifa y fórmula definitiva de cobro','Validar permisos y condiciones de gestión de reservas','Recibir rúbrica y retroalimentación de Evaluación 1'],'En curso':[],'En revisión':['Informe de requerimientos y entrevista simulada','Casos de uso, procesos y modelo de datos','Sketch, wireframes y mockups','Prueba académica del prototipo'],'Terminado':['Conservar los 11 materiales originales','Reconstruir diagramas nativos y enlazar el editor','Implementar pasajeros individuales y costos','Verificar procesos y publicar la entrega']}
kanban=[dict(estado=state,tarea=t) for state,tasks in columns.items() for t in tasks]
(ROOT/'planificacion/kanban.json').write_text(json.dumps(kanban,ensure_ascii=False,indent=2))
(ROOT/'planificacion/kanban.md').write_text('# Kanban · Duerme Bien\n\n| Estado | Tarea |\n|---|---|\n'+'\n'.join(f'| {r["estado"]} | {r["tarea"]} |' for r in kanban)+'\n\nTerminado indica trabajo técnico realizado. La revisión académica y la validación del hotel siguen pendientes.\n')
s=(ROOT/'scripts/construir_modelado.py').read_text();exec(s[:s.index('cases={')]);d=D('kanban','Kanban · Duerme Bien',1600,1080)
for i,(state,tasks) in enumerate(columns.items()):
 x=40+i*390;d.node('col'+str(i),state,x,100,360,850,'frame',fill='#edf4f7')
 for j,t in enumerate(tasks):d.node(f'task{i}-{j}','\n'.join(textwrap.wrap(t,29)),x+15,175+j*185,330,150)
 if not tasks:d.node('none','Sin tareas en curso',x+15,175,330,100)
d.save()
# Portada corta y todos los artefactos visibles, igual que la organización de referencia.
diagrams=[('Casos de uso · Operación','casos-de-uso'),('Casos de uso · Administración','casos-de-uso-administracion'),('Registro de reserva','flujo-reserva'),('Modificación y cancelación','flujo-gestion-reservas'),('Check-in','flujo-check-in'),('Check-out','flujo-check-out'),('Clases de dominio','diagrama-de-clases'),('Modelo lógico de base de datos','modelo-de-datos')]
md='# Sistema de Pasajeros - Hotel Duerme Bien\n\n**Tema 6 · Luis Huenchul**\n\n[Ver entrega]('+site+') · [Abrir prototipo]('+site+'prototipo/)\n\n## Entrega\n\n### 1. Informe de requerimientos\n\n[Informe PDF completo](informe/informe-con-diagramas.pdf) · [Informe editable](informe/requerimientos-y-modelado.md)\n'
for i,(name,key) in enumerate(diagrams,2):md+=f'\n### {i}. {name}\n\n![{name}](diagramas/{key}.svg)\n\n[Ver imagen](diagramas/{key}.svg) · [PDF](diagramas/{key}.pdf) · [Editar]({edit(key)})\n'
md+='\n### 10. Sketch\n\n![Sketch](mockups/sketch.svg)\n\n[Editar]('+edit('sketch')+')\n\n### 11. Wireframes y mockups\n\n[Ver las nueve pantallas]('+site+'mockups/) · [Editar todas las vistas]('+edit('interfaces')+')\n\n| Pantalla | Wireframe | Mockup | Editar |\n|---|---|---|---|\n'
for key,name in M['pantallas']:md+=f'| {name} | ![{name}](mockups/wireframe-{key}.svg) | ![{name}](mockups/mockup-{key}.svg) | [Wireframe]({edit("wireframe-"+key)}) · [Mockup]({edit("mockup-"+key)}) |\n'
md+='\n### 12. Prototipo funcional\n\n[Abrir prototipo]('+site+'prototipo/) · [Editar código](https://github.dev/Yutre3/hotel-duerme-bien/tree/main/prototipo)\n\n![Cuenta individual verificada](evidencia/cuenta-verificada.jpg)\n\n### 13. Kanban\n\n![Kanban](diagramas/kanban.svg)\n\n[Ver tablero](planificacion/kanban.md) · [Editar]('+edit('kanban')+')\n\n### Materiales y referencias\n\n[Materiales originales]('+repo+'/tree/main/fuentes) · [Referencias técnicas](informe/requerimientos-y-modelado.md#12-referencias) · [Repositorio de referencia](https://github.com/Yutre3/diego) · [Pruebas](tests/prototipo.test.cjs)\n'
(ROOT/'README.md').write_text(md)
css='''body{font-family:Arial,sans-serif;max-width:1180px;margin:32px auto;padding:0 24px;color:#163b50;line-height:1.6}h1{font-size:32px}h2{border-top:1px solid #d8e2e7;margin-top:45px;padding-top:22px}h3{font-size:21px}a{color:#126479}nav,.links{display:flex;gap:18px;flex-wrap:wrap}.diagram{display:block;max-width:100%;height:auto;border:1px solid #d8e2e7;cursor:zoom-in}.tools{margin:12px 0 32px;display:flex;gap:18px;flex-wrap:wrap}iframe{width:100%;height:1100px;border:1px solid #d8e2e7}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.tile{border:1px solid #d8e2e7;padding:12px}.tile img{max-width:100%;height:auto}.tile h3{margin:0 0 8px}@media(max-width:750px){.grid{grid-template-columns:1fr 1fr}h1{font-size:26px}iframe{height:950px}}'''
page=f'<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Duerme Bien · Tema 6</title><style>{css}</style></head><body><h1>Sistema de Pasajeros - Hotel Duerme Bien</h1><p>Tema 6 · Luis Huenchul</p><nav><a href="informe/informe-con-diagramas.pdf">Informe completo</a><a href="prototipo/">Prototipo</a><a href="mockups/">Wireframes y mockups</a><a href="{repo}">Repositorio</a></nav><h2>Casos de uso y procesos</h2>'
for name,key in diagrams:
 page+=f'<h3>{name}</h3><a href="diagramas/{key}.svg" target="_blank" rel="noopener"><img class="diagram" src="diagramas/{key}.svg" alt="{name}" loading="lazy"></a><p class="tools"><a href="diagramas/{key}.pdf">PDF</a><a href="{edit(key)}" target="_blank" rel="noopener">Editar en diagrams.net</a></p>'
page+=f'<h2>Sketch</h2><img class="diagram" src="mockups/sketch.svg" alt="Sketch"><p class="tools"><a href="{edit("sketch")}" target="_blank" rel="noopener">Editar sketch</a></p><h2>Wireframes y mockups</h2><p class="tools"><a href="mockups/">Abrir galería completa</a><a href="{edit("interfaces")}" target="_blank" rel="noopener">Editar todas las vistas</a></p><div class="grid">'
for key,name in M['pantallas']:
 page+=f'<section class="tile"><h3>{name}</h3><a href="mockups/mockup-{key}.svg" target="_blank" rel="noopener"><img src="mockups/mockup-{key}.svg" alt="Mockup de {name}" loading="lazy"></a><div class="links"><a href="mockups/wireframe-{key}.svg">Wireframe</a><a href="{edit("mockup-"+key)}" target="_blank" rel="noopener">Editar mockup</a></div></section>'
page+=f'</div><h2>Prototipo funcional</h2><p class="tools"><a href="prototipo/">Abrir prototipo</a><a href="https://github.dev/Yutre3/hotel-duerme-bien/tree/main/prototipo">Editar código</a></p><iframe src="prototipo/" title="Prototipo de Duerme Bien" loading="lazy"></iframe><h2>Kanban</h2><img class="diagram" src="diagramas/kanban.svg" alt="Kanban"><p class="tools"><a href="planificacion/kanban.md">Ver tareas</a><a href="{edit("kanban")}" target="_blank" rel="noopener">Editar tablero</a></p><h2>Materiales y referencias</h2><p class="links"><a href="{repo}/tree/main/fuentes">Materiales originales</a><a href="{repo}/blob/main/informe/requerimientos-y-modelado.md#12-referencias">Referencias técnicas</a><a href="{repo}/tree/main/tests">Pruebas</a></p></body></html>'
(ROOT/'index.html').write_text(page)
