from pathlib import Path
import json,re,html
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak,KeepTogether
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import fitz
ROOT=Path(__file__).resolve().parents[1];M=json.loads((ROOT/'modelo/sistema.json').read_text())
requirements=[('RF01','Gestionar habitaciones','Registrar número único, capacidad entera positiva y orientación. Editar sin invalidar reservas o estadías vigentes.','CU02','Habitacion','habitaciones'),('RF02','Registrar e identificar huéspedes','Guardar identificación única, nombres y apellidos; seleccionar huéspedes existentes para evitar duplicarlos. Asociar cada pasajero a su estadía.','CU03, CU04','Huesped, EstadiaHuesped','huespedes, checkin'),('RF03','Consultar ocupación y disponibilidad','Mostrar ocupación actual y habitaciones compatibles con fechas y cantidad de pasajeros. Considerar reservas vigentes y estadías activas.','CU04, CU05, CU09, CU11','Habitacion, Reserva, Estadia','disponibilidad'),('RF04','Registrar check-in','Permitir ingreso con o sin reserva. Verificar habitación, intervalo y todos los pasajeros; crear estadía activa y asignaciones individuales.','CU04','Estadia, EstadiaHuesped','checkin'),('RF05','Registrar check-out','Seleccionar estadía activa, revisar la cuenta y confirmar la salida. Conservar historial y liberar ocupación.','CU06','Estadia, EstadiaHuesped','checkout'),('RF06','Calcular costos por pasajero','Obtener huéspedes de la estadía, aplicar la regla de cobro y mostrar cada costo y total. Conservar los resultados individuales.','CU06, CU07','EstadiaHuesped','checkout'),('RF07','Gestionar usuarios y perfiles','Registrar usuarios, asignar Administrador o Encargado, controlar operaciones por perfil y estado activo.','CU01, CU08','Usuario, Rol','acceso, usuarios'),('RF08','Gestionar reservas','Registrar titular, habitación, fechas y cantidad. Modificar o cancelar sólo reservas registradas; comprobar disponibilidad antes de guardar.','CU09, CU11, CU12','Reserva, Habitacion, Huesped','reservas'),('RF09','Generar informes','Consultar ocupación y reservas para un período; mostrar habitación, fechas, pasajeros y estado; representar también resultados vacíos.','CU10','Reserva, Estadia, Habitacion','informes')]
specs={
'CU01':('Administrador y Encargado','Usuario registrado y activo.','1. Ingresar identificación y credencial.\n2. Validar identidad y estado.\n3. Recuperar rol y permisos.\n4. Abrir sesión y navegación autorizada.','A1. Credencial incorrecta o usuario inactivo: rechazar el ingreso y permitir corregir.','Sesión activa con el perfil asignado.','En el prototipo se selecciona un usuario demo; no se implementa la autenticación productiva.'),
'CU02':('Administrador','Sesión con permiso de administración.','1. Seleccionar registro nuevo o habitación existente.\n2. Ingresar número, capacidad y orientación.\n3. Validar número único y capacidad.\n4. Si es edición, revisar registros vigentes.\n5. Guardar y actualizar el listado.','A1. Datos inválidos o número duplicado: corregir.\nA2. Habitación con reserva registrada o estadía activa: no modificar sus características en la propuesta.','Habitación registrada o actualizada.','RF01; la restricción de edición es una propuesta para proteger asignaciones existentes.'),
'CU03':('Encargado; Administrador por herencia de interacciones','Sesión con permiso.','1. Ingresar identificación, nombres y apellidos.\n2. Buscar coincidencia de identificación.\n3. Registrar un nuevo huésped.\n4. Mostrar el registro para seleccionarlo en reserva o check-in.','A1. Identificación ya existente: informar y seleccionar el huésped registrado.\nA2. Datos incompletos: corregir.','Huésped identificado sin duplicación.','El tipo de identificación se valida en la entrevista; no se exige RUT sin evidencia del caso.'),
'CU04':('Encargado; Administrador por herencia de interacciones','Sesión con permiso; huéspedes registrados. Si se usa reserva, debe estar REGISTRADA.','1. Seleccionar reserva o ingreso directo.\n2. Definir habitación y fechas o recuperar las de la reserva.\n3. Identificar a todos los huéspedes.\n4. Verificar fechas, duplicados y ausencia de otra estadía activa de esos huéspedes.\n5. Incluir CU05: consultar disponibilidad y capacidad.\n6. Confirmar ingreso.\n7. Crear ESTADIA ACTIVA y una participación por huésped.\n8. Si corresponde, pasar reserva a CHECK_IN.','A1. Reserva cancelada o ya utilizada: seleccionar otra o ingreso directo.\nA2. Faltan pasajeros identificados, fechas inválidas o huésped ya alojado: corregir.\nA3. Capacidad insuficiente o conflicto: elegir otra habitación o intervalo.\nA4. No confirmar: terminar sin guardar.','Estadía activa con sus pasajeros; habitación ocupada.','La disponibilidad es una validación del flujo, no una precondición asumida como cierta.'),
'CU05':('Encargado; Administrador por herencia de interacciones','Sesión con permiso.','1. Ingresar entrada, salida y cantidad.\n2. Validar intervalo y cantidad entera positiva.\n3. Filtrar habitaciones por capacidad.\n4. Excluir reservas REGISTRADAS/CHECK_IN y estadías ACTIVA que se superpongan.\n5. Mostrar habitaciones compatibles.','A1. Fechas inválidas: corregir.\nA2. Sin resultados: mostrar listado vacío y permitir otra consulta.','Disponibilidad consultable para el intervalo.','Puede ejecutarse directamente o como inclusión de CU04, CU09 y CU11.'),
'CU06':('Encargado; Administrador por herencia de interacciones','Sesión con permiso y estadía ACTIVA.','1. Seleccionar estadía y salida real.\n2. Recuperar todos sus pasajeros.\n3. Incluir CU07: calcular cuenta individual y total.\n4. Mostrar detalle de cuenta.\n5. Confirmar cuenta y salida.\n6. Revisar posibles conflictos al extender la salida.\n7. Guardar costos individuales y salida real.\n8. Pasar estadía y reserva asociada a FINALIZADA.\n9. Liberar ocupación de habitación.','A1. Estadía no activa o salida inválida: rechazar.\nA2. Regla o tarifa sin definir: solicitar definición antes de cerrar.\nA3. No confirmar: conservar estadía activa.\nA4. Extensión de salida con conflicto: resolverlo antes de guardar.','Estadía finalizada, cuenta conservada y habitación liberada.','La liberación no elimina reservas futuras ni historial.'),
'CU07':('Invocado por CU06','Estadía activa, pasajeros identificados y regla de cobro definida.','1. Recuperar período y pasajeros.\n2. Obtener parámetros de la regla aprobada.\n3. Calcular costo de cada pasajero.\n4. Sumar los costos para obtener total.\n5. Presentar el detalle para revisión.','A1. Regla, tarifa o período inválido: no producir una cuenta confirmable.\nA2. Importe fuera del rango admitido: rechazar el cálculo.','Cuenta calculada, sin finalizar todavía la estadía.','En la demostración: noches = salida - entrada; costo individual = tarifa de prueba x noches. El caso no confirma esta fórmula.'),
'CU08':('Administrador','Sesión con permiso administrativo.','1. Seleccionar nuevo usuario o existente.\n2. Ingresar nombre de usuario.\n3. Asignar rol Administrador o Encargado.\n4. Indicar estado activo en edición.\n5. Validar y guardar.','A1. Nombre duplicado o rol inexistente: corregir.\nA2. Cambio del propio rol/estado durante sesión: rechazar en la propuesta.','Usuario guardado con un rol válido.','Las credenciales seguras pertenecen a la implementación final; el prototipo usa usuarios demo.'),
'CU09':('Encargado; Administrador por herencia de interacciones','Sesión con permiso y titular registrado.','1. Seleccionar titular y habitación.\n2. Ingresar entrada, salida y cantidad.\n3. Validar datos.\n4. Incluir CU05 para fechas y capacidad.\n5. Confirmar.\n6. Guardar reserva REGISTRADA y mostrar su número.','A1. Fecha, cantidad o titular inválidos: corregir.\nA2. Conflicto de disponibilidad: cambiar selección.\nA3. No confirmar: no crear reserva.','Reserva registrada; ocupación actual de habitación no cambia.','La reserva bloquea el intervalo futuro, no marca la habitación como ocupada físicamente.'),
'CU10':('Administrador','Sesión con permiso y período válido.','1. Seleccionar fechas desde/hasta.\n2. Consultar estadías que intersectan el período.\n3. Mostrar informe de ocupación con pasajeros y estados.\n4. Consultar reservas que intersectan el período.\n5. Mostrar titular, habitación, fechas y estado.','A1. Período inválido: corregir.\nA2. Sin datos: mostrar informe vacío, no un error.','Informes visibles para el período.','Las reservas CANCELADAS se conservan en el informe histórico con su estado.'),
'CU11':('Encargado; Administrador por herencia de interacciones','Sesión con permiso y reserva REGISTRADA.','1. Seleccionar reserva.\n2. Cambiar habitación, titular, fechas o cantidad.\n3. Validar campos.\n4. Incluir CU05 excluyendo la propia reserva del conflicto.\n5. Confirmar y guardar cambios.','A1. Reserva en otro estado: impedir modificación.\nA2. Capacidad o disponibilidad incompatibles: corregir sin perder la reserva original.\nA3. No confirmar: conservar valores originales.','Reserva actualizada y todavía REGISTRADA.','No se modifica una reserva ya usada para check-in.'),
'CU12':('Encargado; Administrador por herencia de interacciones','Sesión con permiso y reserva REGISTRADA.','1. Seleccionar reserva.\n2. Solicitar cancelación.\n3. Confirmar la decisión.\n4. Marcar CANCELADA.\n5. Liberar su bloqueo de disponibilidad sin borrar historial.','A1. Reserva en otro estado: impedir cancelación.\nA2. No confirmar: conservar reserva registrada.','Reserva cancelada, conservada en el historial.','La cancelación no se modela como extend obligatorio ni como borrado de datos.')}
parts=[]
def add(t):parts.append(t)
def table(heads,rows):return '| '+' | '.join(heads)+' |\n| '+' | '.join(['---']*len(heads))+' |\n'+'\n'.join('| '+' | '.join(map(str,row))+' |' for row in rows)
add('# Sistema de Pasajeros de Hotel - Duerme Bien\n\nTema 6 · Luis Huenchul\n\nInforme de requerimientos y modelado')
add('## 1. Introducción\n\n### 1.1 Propósito\nDefinir qué debe hacer el sistema que reemplazará las planillas Excel del hotel Duerme Bien y relacionar requerimientos, casos de uso, procesos, datos e interfaces. Se utilizan las secciones IEEE 830 adaptadas enumeradas en el documento de definición de proyectos.\n\n### 1.2 Alcance\nHabitaciones, huéspedes, ocupación y disponibilidad, check-in, check-out, costos por pasajero, reservas, usuarios y los informes de ocupación y reservas. Se conserva el tema 6; no se agregan pagos electrónicos, restaurante, inventario ni otros servicios.\n\n### 1.3 Público objetivo\nAdministrador y encargados del hotel, equipo de desarrollo y docente.\n\n### 1.4 Definiciones\nHuésped: pasajero identificado. Reserva: alojamiento previsto para un período. Estadía: alojamiento efectivamente registrado. Participación: vínculo entre una estadía y uno de sus huéspedes. Check-in: ingreso y asignación. Check-out: cálculo de cuenta y cierre. Wireframe: estructura de pantalla. Mockup: diseño visual. Prototipo: interfaz que permite probar el flujo.')
add('## 2. Descripción general\n\n### 2.1 Perspectiva del producto\nEl sistema centraliza la información hoy mantenida en Excel. Las habitaciones conservan capacidad y orientación; las reservas y estadías conservan su historial. La disponibilidad se obtiene de los registros vigentes, en lugar de guardar un estado futuro ambiguo en la habitación.\n\n### 2.2 Funciones generales\nRegistro y edición de habitaciones, registro de huéspedes, consulta de disponibilidad, asignación de huéspedes, cierre de estadías, cálculo individual, reservas, gestión de perfiles e informes.\n\n### 2.3 Clases de usuario\nEl caso identifica Administrador y Encargado. En el diagrama de casos de uso, Administrador generaliza a Encargado y agrega las tareas administrativas. En el diagrama de clases ambos especializan a la clase abstracta Usuario para hacer visible la herencia solicitada por la pauta. En el modelo relacional esa especialización se implementa mediante USUARIO y ROL, evitando duplicar credenciales.\n\n### 2.4 Entorno operativo\nEl prototipo usa HTML, CSS y JavaScript en el navegador, con almacenamiento local. Implementa operaciones y validaciones para demostrar el diseño. La selección de usuario simula una sesión; no autentica identidades reales. El sistema final necesita servidor, base de datos, control transaccional y autenticación segura. El caso no fija motor ni infraestructura.\n\n### 2.5 Restricciones\nMantener capacidad, orientación, asignación de pasajeros, cálculo individual, ambos perfiles e informes. No inventar tarifas ni entrevistas reales. Los ejemplos son ficticios y los importes se expresan en CLP.\n\n### 2.6 Supuestos y dependencias\nSe propone una habitación completa por reserva y estadía; cada estadía identifica a todos sus pasajeros. Los intervalos se interpretan como [entrada, salida): una salida permite otra entrada ese día. Compartir habitación entre estadías, reservas de varias habitaciones, permisos exactos y regla de cobro requieren confirmación. El diseño se ajustará si la entrevista define esas condiciones de otra forma.')
add('## 3. Requerimientos\n\n### 3.1 Requerimientos funcionales\n'+table(['ID','Requerimiento','Criterio observable'],[(a,b,c) for a,b,c,*_ in requirements]))
add('### 3.2 Requerimientos no funcionales propuestos\n'+table(['ID','Criterio','Aceptación'],[('RNF01','Acceso por perfil','Rechazar una operación restringida aun si se intenta fuera de la navegación visible.'),('RNF02','Integridad de datos','Rechazar duplicados, fechas incoherentes, capacidades inválidas y pasajeros no identificados.'),('RNF03','Usabilidad','Etiquetas, navegación consistente, detalle de cuenta y mensajes concretos de corrección.'),('RNF04','Persistencia','Los datos de demostración sobreviven al recargar el navegador; el sistema final usa almacenamiento central.'),('RNF05','Consistencia concurrente','El sistema final confirma disponibilidad y guarda asignación en una transacción. El prototipo local no demuestra concurrencia entre dispositivos.'),('RNF06','Trazabilidad y mantenimiento','Conservar un código único por caso de uso y la relación con requerimientos, datos y pantallas.')]))
add('### 3.3 Matriz de permisos propuesta\n'+table(['Operación','Encargado','Administrador'],[('Acceso y consulta de disponibilidad','Sí','Sí'),('Huéspedes, reservas, check-in y check-out','Sí','Sí'),('Gestión de habitaciones','No','Sí'),('Gestión de usuarios','No','Sí'),('Informes de ocupación y reservas','No','Sí')]))
add('## 4. Reglas de negocio\n'+table(['ID','Regla','Origen'],[('RN01','Pasajeros de una estadía <= capacidad de habitación.','Derivada del control de capacidad.'),('RN02','No confirmar reservas o estadías con intervalos incompatibles en la misma habitación.','Derivada de disponibilidad.'),('RN03','Cada pasajero se registra individualmente en ESTADIA_HUESPED; no se guarda sólo una cantidad.','Derivada de registro y costo por pasajero.'),('RN04','Check-out incluye calcular cuenta por pasajero y requiere confirmación antes de cerrar.','Imagen UML del hotel y diseño del proceso.'),('RN05','Reserva REGISTRADA pasa a CHECK_IN al ingresar; al salir pasa a FINALIZADA. CANCELADA deja de bloquear disponibilidad.','Estados propuestos para gestionar reservas.'),('RN06','Sólo una estadía ACTIVA puede cerrarse. La salida libera ocupación y conserva historial.','Proceso de check-out.'),('RN07','Cada usuario tiene un rol válido: Administrador o Encargado.','Perfiles explícitos del tema 6.'),('RN08','Un huésped no se asigna a dos estadías activas simultáneas.','Propuesta de integridad de asignación.'),('RN09','No borrar reservas canceladas ni estadías finalizadas para liberar una habitación.','Propuesta para conservar los informes históricos.')]))
add('### 4.1 Cálculo de costos\nEl caso exige cálculo automático por pasajero, pero no entrega tarifa ni unidad de cobro. Para demostrar la operación se ingresa una tarifa ficticia por pasajero y noche. Las noches se calculan a partir de las fechas; costo individual = tarifa de prueba x noches y total = suma de los costos individuales. Se conserva la tarifa aplicada y el costo en cada participación; las noches comunes de la cuenta se guardan una sola vez en ESTADIA. Esto no confirma la política real de cobro. No se agregan impuestos, descuentos ni pagos que no estén en el caso.')
add('## 5. Toma de requerimientos\n\n### 5.1 Ejercicio de entrevista simulada\nLa actividad solicita entrevista simulada. El siguiente registro organiza preguntas y respuestas sustentadas en el caso escrito; no representa una conversación que haya ocurrido con el hotel. Las respuestas que no constan en el caso quedan pendientes.\n'+table(['Pregunta','Respuesta del cliente simulado basada en el caso','Trazabilidad'],[('¿Qué se quiere reemplazar?','Las planillas Excel usadas para habitaciones y pasajeros.','Propósito'),('¿Qué se registra de habitaciones?','Capacidad y orientación; se propone un número único para identificarlas.','RF01'),('¿Qué se controla de los pasajeros?','Su registro y asignación a habitaciones, ocupación y costos.','RF02-RF06'),('¿Qué usuarios existen?','Administrador y encargados del hotel.','RF07'),('¿Qué informes se necesitan?','Ocupación y reservas.','RF09'),('¿Qué tarifa y fórmula utiliza el hotel?','El caso no las define; confirmar antes de implementar el cobro final.','RF06'),('¿Se reserva una habitación completa o camas?','No consta; el diseño propone habitación completa.','RF03, RF08'),('¿Qué permisos exactos tiene cada perfil?','No consta; validar la matriz propuesta.','RF07')]))
add('### 5.2 Preguntas pendientes\n'+table(['ID','Pregunta','Afecta'],[('P01','¿Qué tipo de identificación y datos personales son obligatorios?','RF02'),('P02','¿Tarifa por noche/día? ¿Puede variar por huésped, habitación o período?','RF06'),('P03','¿Habitaciones compartidas o una habitación por estadía?','RF03, RF04'),('P04','¿Varias habitaciones por reserva?','RF08'),('P05','¿Cambios de habitación durante la estadía?','RF04'),('P06','¿Permisos definitivos por rol?','RF07'),('P07','¿Condiciones definitivas para modificar/cancelar y extender salidas?','RF05, RF08'),('P08','¿Campos y filtros exactos de informes?','RF09'),('P09','¿Entorno final, respaldo y concurrencia?','RNF04, RNF05'),('P10','¿Cuál fue la retroalimentación detallada de la Evaluación 1?','Evaluación 2')]))
add('## 6. Factibilidad\n\n### 6.1 Técnica\nEl prototipo verifica que los procesos pueden expresarse mediante formularios, reglas y relaciones entre registros. El modelo usa siete entidades relacionales y una tabla de unión para pasajeros. El sistema final requiere transacciones para impedir doble asignación, credenciales seguras y persistencia central. El navegador local permite revisar funcionalidades, pero no sustituye esas capacidades.\n\n### 6.2 De negocio\nLa propuesta responde al objetivo de centralizar el registro, evitar duplicados y consultar ocupación y reservas. No se calculan costos de implementación, ahorros ni rentabilidad porque el caso no entrega datos económicos. La factibilidad final depende de validar reglas y entorno con el cliente simulado.')
add('## 7. Modelado funcional\n\n### 7.1 Casos de uso\nUn diagrama único muestra el límite del sistema, los dos actores y CU01-CU12. Las asociaciones actor-caso son continuas y sin flecha. Las inclusiones son discontinuas, con flecha hacia el caso incluido. CU04, CU09 y CU11 incluyen consultar disponibilidad; CU06 incluye calcular cuenta. Ingreso directo extiende CU04 sólo bajo la condición sin reserva, por lo que no modifica el flujo normal. El Administrador especializa al actor Encargado mediante triángulo hueco hacia Encargado. El Huésped es una entidad atendida por los encargados, no un usuario directo del sistema.')
for id,name,rf in M['casos']:
 actor,pre,flow,alt,post,note=specs[id];add(f'### {id} - {name}\n\nActor: {actor}.\n\nPrecondiciones: {pre}\n\nFlujo principal:\n{flow}\n\nAlternativas y errores:\n{alt}\n\nPostcondición: {post}\n\nTrazabilidad: {rf}.\n\nObservación: {note}')
add('### 7.2 Procesos\nLos flujos muestran inicio/fin, entradas/salidas, acciones, decisiones con salidas etiquetadas, retornos por error y finalización sin cambios. Se separan registrar reserva, check-in, check-out y modificar/cancelar reserva. Cada decisión tiene dos salidas. Cancelar una operación conserva el registro original; cancelar una reserva cambia su estado, no borra su historial.')
add('## 8. Clases y modelo de datos\n\n### 8.1 Clases de dominio\nUsuario es una clase abstracta y Administrador/Encargado heredan sus datos de acceso. Administrador genera informes de ocupación y reservas. Un Huesped puede ser titular de reservas y tener participaciones históricas; cada Reserva se asigna a una Habitacion y puede originar una Estadia. Habitacion aloja estadías y Estadia compone una o más ParticipacionEstadia con rombo sólido. Las demás relaciones son asociaciones. Cada relación incluye un verbo y multiplicidades junto a sus extremos; las clases muestran atributos privados, métodos públicos y tipos.')
add('### 8.2 Diccionario y claves\n'+table(['Entidad','Clave primaria','Referencias y unicidad','Uso'],[('ROL','id_rol','nombre único','Administrador o Encargado.'),('USUARIO','id_usuario','id_rol -> ROL; nombre_usuario único','Perfil, estado y credencial del sistema final.'),('HABITACION','id_habitacion','numero único','Capacidad positiva y orientación.'),('HUESPED','id_huesped','identificacion única','Identidad, nombres y apellidos.'),('RESERVA','id_reserva','id_habitacion -> HABITACION; id_huesped_titular -> HUESPED','Fechas, cantidad y estado.'),('ESTADIA','id_estadia','id_habitacion -> HABITACION; id_reserva opcional y único -> RESERVA','Fechas reales/previstas, estado y noches cobradas.'),('ESTADIA_HUESPED','(id_estadia, id_huesped)','id_estadia -> ESTADIA; id_huesped -> HUESPED','Cada pasajero; tarifa aplicada y costo histórico.')]))
add('### 8.3 Cardinalidades y restricciones\n'+table(['Relación','Cardinalidad','Interpretación'],[('ROL - USUARIO','1 : 0..*','Un usuario tiene exactamente un rol; un rol puede no tener usuarios.'),('HABITACION - RESERVA','1 : 0..*','Una reserva tiene una habitación; una habitación tiene muchas reservas en el tiempo.'),('HABITACION - ESTADIA','1 : 0..*','Una estadía tiene una habitación; una habitación conserva distintas estadías históricas.'),('HUESPED - RESERVA','1 : 0..*','Una reserva tiene un titular; un huésped puede titularizar varias reservas.'),('RESERVA - ESTADIA','0..1 : 0..1','Una reserva origina como máximo una estadía; puede existir estadía sin reserva.'),('ESTADIA - ESTADIA_HUESPED','1 : 1..*','Cada estadía registrada tiene uno o más pasajeros.'),('HUESPED - ESTADIA_HUESPED','1 : 0..*','Cada participación identifica un huésped; el huésped puede alojarse varias veces.')]))
add('El modelo lógico usa notación pata de cuervo, claves PK/FK/UQ y tipos de datos propuestos. NULL identifica información todavía no definida: reserva de origen de un ingreso directo, salida real de una estadía activa y resultados de cobro antes de cerrar. El resto de los campos de identificación y referencias obligatorias debe ser NOT NULL. Las fechas deben respetar salida > entrada; capacidad y cantidad son enteros positivos. La pareja de ESTADIA_HUESPED es única. Capacidad, superposición y mínimo de un pasajero requieren validación conjunta/transaccional: una FK aislada no garantiza esas reglas.')
add('### 8.4 Normalización\n\nPrimera forma normal: cada celda almacena un valor. Los pasajeros de una estadía no se guardan en una lista dentro de HABITACION; cada participación es una fila de ESTADIA_HUESPED.\n\nSegunda forma normal: las tablas de identificación tienen claves simples. En la tabla de unión, los datos personales dependen de id_huesped y se mantienen en HUESPED; fechas y noches comunes dependen de id_estadia y se mantienen en ESTADIA. La tarifa aplicada y el costo histórico se vinculan a la participación completa.\n\nTercera forma normal: nombre del rol está en ROL; capacidad y orientación están en HABITACION; nombres del titular están en HUESPED. Esos datos no se repiten en RESERVA o ESTADIA. La ocupación y el total de cuenta se derivan, en lugar de duplicarlos como fuentes de verdad. El costo individual se conserva como resultado histórico de una regla de cobro aplicada; la tarifa de referencia no es una tabla de precios del hotel. La regla real podría requerir otra estructura una vez validada.')
add('## 9. Sketch, wireframes, mockups y prototipo\n\nSketch: distribución inicial de cabecera, navegación, indicadores, formulario y resultados. Wireframes: nueve pantallas con campos, controles, listados y acciones sin depender del estilo visual. Mockups: las mismas nueve pantallas con identidad gráfica y ejemplos de datos. Prototipo: navegación y operaciones con persistencia local y validaciones del modelo.\n'+table(['Pantalla','Datos y acciones principales','Casos de uso'],[('Acceso','Selección de usuario demo y perfil asignado.','CU01'),('Disponibilidad','Fechas, cantidad, capacidad y habitaciones compatibles; ocupación actual.','CU05'),('Habitaciones','Número, capacidad, orientación; registrar y editar.','CU02'),('Huéspedes','Identificación, nombres y apellidos; registro y selección posterior.','CU03'),('Reservas','Titular, habitación, fechas, cantidad; registrar, modificar, cancelar.','CU09, CU11, CU12'),('Check-in','Reserva o ingreso directo; habitación, fechas y cada pasajero.','CU04'),('Check-out','Estadía, salida, tarifa ficticia, cálculo individual, total y confirmación.','CU06, CU07'),('Informes','Período, ocupación y reservas con estados.','CU10'),('Usuarios','Nombre único, perfil y estado; registrar y editar.','CU08')]))
add('### 9.1 Archivos editables\nLos diagramas y todas las vistas de interfaz tienen archivos nativos .drawio con figuras, textos y conectores unidos a los elementos; no son imágenes pegadas en un lienzo. La galería permite abrir cada archivo directamente en diagrams.net. interfaces.drawio reúne sketch y las dieciocho vistas de wireframe/mockup. Los enlaces de edición de código usan github.dev. El material de mockups menciona distintas plataformas, incluido Cacoo, Balsamiq y prototipos HTML/CSS. Se conserva diagrams.net porque es el formato del repositorio de referencia. No se afirma haber creado proyectos en plataformas distintas.')
add('### 9.2 Alcance implementado\nEl prototipo registra y edita habitaciones, identifica huéspedes, gestiona reservas, realiza check-in con o sin reserva, registra cada pasajero, calcula noches a partir de fechas y conserva costos individuales al salir. Controla las operaciones por rol demo y genera informes por período. No implementa autenticación productiva, servidor, base de datos central ni exclusión concurrente entre dispositivos. Estas diferencias se mantienen visibles en la documentación para no presentar una maqueta como un sistema instalado en el hotel.')
add('## 10. Planificación Kanban\n\nEl tablero conserva tareas técnicas terminadas, artefactos en revisión y decisiones pendientes. Terminar la implementación no equivale a aprobación del docente. No se inventan integrantes ni plazos. La pauta de la Evaluación 2 fue revisada; las decisiones sobre identificación, cobro, permisos, habitación compartida y entorno, además de la retroalimentación detallada de la Evaluación 1, permanecen por validar.')
add('## 11. Trazabilidad\n'+table(['RF','Casos de uso','Clases/entidades','Pantallas'],[(a,d,e,f) for a,b,c,d,e,f in requirements]))
add('### 11.1 Verificación\nLas pruebas del motor comprueban acceso restringido, duplicados, capacidad, fechas, solapamiento, intervalos contiguos, modificación/cancelación de reservas, identificación de todos los pasajeros, check-in directo, repetición de operaciones, costos por huésped, liberación de ocupación e informes por fechas. La revisión del modelado comprueba códigos de casos, cobertura de requisitos, conectores, decisiones y cardinalidades. Las pruebas técnicas no reemplazan la aprobación académica ni la validación de reglas del hotel.')
add('## 12. Referencias\n\nMateriales del profesor utilizados: Evaluación_2_MSI.pdf; Definición de proyectos(2).docx; UML_CASOS_DE_USO_2(2).jpg; UML_CASOS_DE_USO(2).jpg; CASOS_DE_USO_como_iniciar(2).pdf; CASOS_DE_USO_extend_y_include(2).pdf; diagrama_de_procesos(2).jpg; Diagramas de Clase(2).pdf; GUIA_diagramas_de_clase(2).pdf; MODELO_E_R_NORMALIZACION(1).pdf; MOCKUP_COMPLETO(2).pdf; Github_Git_VSCode(1).docx. Se conservan los originales en fuentes/.\n\nReferencias técnicas de notación y diseño consultadas para la revisión:\n1. OMG. UML 2.5.1: https://www.omg.org/spec/UML/2.5.1\n2. draw.io. Clases UML: https://www.drawio.com/docs/diagram-types/uml/class-diagrams/\n3. draw.io. Modelo entidad-relación: https://www.drawio.com/docs/diagram-types/entity-relationship-tables/\n4. Balsamiq. Wireframes: https://balsamiq.com/blog/what-are-wireframes/\n5. Referencia de organización y prototipo inicial: https://github.com/Yutre3/diego\n\nEstas referencias aportan notación y técnicas, no funciones nuevas del negocio. El alcance proviene del tema 6 y de la pauta de Evaluación 2. No se agregan funciones que no estén sustentadas por esos materiales.')
text='\n\n'.join(parts)+'\n';(ROOT/'informe/requerimientos-y-modelado.md').write_text(text)
# PDF legible, con tablas que se repiten correctamente al cambiar de página.
font='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf';bold='/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'
pdfmetrics.registerFont(TTFont('DV',font));pdfmetrics.registerFont(TTFont('DVB',bold));styles=getSampleStyleSheet()
for key in ['BodyText','Heading1','Heading2','Heading3']:styles[key].fontName='DVB' if key.startswith('Heading') else 'DV'
styles['BodyText'].fontSize=9;styles['BodyText'].leading=14;styles['BodyText'].spaceAfter=5;styles['Heading1'].fontSize=20;styles['Heading2'].fontSize=14;styles['Heading2'].spaceBefore=14;styles['Heading3'].fontSize=11;styles['Heading3'].spaceBefore=10
story=[]
def p(s,style='BodyText'):return Paragraph(html.escape(s).replace('\n','<br/>'),styles[style])
def add_table(lines):
 rows=[line.strip().strip('|').split('|') for line in lines if '---' not in line]
 width=499/len(rows[0]);cells=[[p(cell.strip()) for cell in row] for row in rows];t=Table(cells,colWidths=[width]*len(rows[0]),repeatRows=1,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e6eff4')),('GRID',(0,0),(-1,-1),.4,colors.HexColor('#bdcbd4')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]));story.extend([t,Spacer(1,12)])
lines=text.splitlines();i=0;buffer=[]
def flush():
 if buffer:story.append(p('\n'.join(buffer)));buffer.clear()
while i<len(lines):
 line=lines[i]
 if not line.strip():flush();i+=1;continue
 if line.startswith('|'):
  flush();rows=[]
  while i<len(lines) and lines[i].startswith('|'):rows.append(lines[i]);i+=1
  add_table(rows);continue
 if line.startswith('#'):
  flush();level=len(line)-len(line.lstrip('#'));story.append(p(line.lstrip('# ').strip(),'Heading'+str(min(level,3))))
 else:buffer.append(line)
 i+=1
flush()
def footer(c,doc):c.setFont('DV',8);c.setFillColor(colors.HexColor('#546778'));c.drawString(48,25,'Duerme Bien · Tema 6 · Luis Huenchul');c.drawRightString(547,25,str(doc.page))
SimpleDocTemplate(str(ROOT/'informe/requerimientos-y-modelado.pdf'),pagesize=A4,leftMargin=48,rightMargin=48,topMargin=42,bottomMargin=42,title='Duerme Bien - Requerimientos y modelado',author='Luis Huenchul').build(story,onFirstPage=footer,onLaterPages=footer)
out=fitz.open(ROOT/'informe/requerimientos-y-modelado.pdf')
for key in ['sistema-casos-de-uso','proceso-completo','diagrama-de-clases','modelo-de-datos','wireframe-completo','mockup-completo','kanban']:
 src=fitz.open(ROOT/'diagramas'/f'{key}.pdf');out.insert_pdf(src);src.close()
out.save(ROOT/'informe/informe-con-diagramas.pdf');out.close()
(ROOT/'modelo/trazabilidad.json').write_text(json.dumps([dict(id=a,nombre=b,criterio=c,casos=d,entidades=e,pantallas=f) for a,b,c,d,e,f in requirements],ensure_ascii=False,indent=2))
